name: Scrape

on:
  schedule:
    - cron: "0 8 * * *" #minute, hour, day, month, year. CronGuru tool, asterisk means "every"
  workflow_dispatch:

jobs: #can change scrape with anything. Just variable name
  scrape: #git push -f origin main;
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 #checkout the repository on a virtual machine that runs ubuntu
    - name: Install pipenv
      run: pipx install pipenv #pipx is github python downloader
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pipenv'
    - run: pipenv install jupyter requests bs4 --python `which python`
    - name: Run scraper
      run: pipenv run jupyter execute scrape.ipynb
    - name: Add and commit
      id: add_commit
      uses: EndBug/add-and-commit@v8
      with:
        committer_name: Automated
        committer_email: actions@users.noreply.github.com
        message: "Latest data"
    - name: Slack Notification on SUCCESS
      if: (success() & steps.add_commit.outputs.committed=='true')
      uses: tokorom/action-slack-incoming-webhook@main
      env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
          text: A successful scrape!
          attachments: |
              [
              {
              "color": "good",
              "author_name": "${{ github.actor }}",
              "author_icon": "${{ github.event.sender.avatar_url }}",
              "fields": [
                  {
                  "title": "GitHub Actions URL",
                  "value": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
                  },
                  {
                  "title": "Commit URL",
                  "value": "https://github.com/${{github.repository}}/commits"
                  }
              ]
              }
              ]
              - name: Slack Notification on FAILURE
              if: failure()
              uses: tokorom/action-slack-incoming-webhook@main
              env:
                  INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              with:
                  text: Something went wrong.
                  attachments: |
                  [
                      {
                      "color": "bad",
                      "author_name": "${{ github.actor }}",
                      "author_icon": "${{ github.event.sender.avatar_url }}",
                      "fields": [
                          {
                          "title": "GitHub Actions URL",
                          "value": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
                          }
                      ]
                      }
                  ]
        - name: Slack Notification on no new commits
              if: (success() & steps.add_commit.outputs.committed=='false')
              uses: tokorom/action-slack-incoming-webhook@main
              env:
                INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              with:
                text: Nothing was committed
